config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :home

  get "/about" => "home#about"

  resources :users, only: [:new, :create, :edit, :update] do
    resources :favourites, only: [:index]
  end

  resources :passwords, only: [:edit, :update, :new] do
    post :link, on: :collection
    get :forgot_password, on: :collection
    patch :update_password, on: :collection
  end
  resources :sessions, only: [:new, :create, :update] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :favourites, only: [:create, :destroy]
    resources :comments
    resources :stars, shallow: true, only: [:create, :update, :destroy]
  end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)

       can :manage, Post do |p|
         p.user == user
       end

       can :delete, Comment do |c|
         c.user == user || c.post.user == user
       end

       cannot :like, Post do |p|
         p.user == user
       end

       can :like, Post do |p|
         user != p.user
       end

       cannot :favourite, Post do |p|
         p.user == user
       end

       can :favourite, Post do |p|
         user != p.user
       end

      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
  # validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {scope: :user_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

   validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  has_many :comments, lambda {order(created_at: :desc)}, dependent: :destroy

  validates :title, presence: true, length: { minimum: 7 }
  validates :body, presence: true

  belongs_to :category

  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user


  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :stars, dependent: :destroy
  has_many :star_raters, through: :stars, source: :user

  


  def body_snippet
    if self.body.length > 100
      return self.body[0...100] + "..."
    else
      return self.body
    end
  end

end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true, uniqueness: {scope: :post_id}
  validates :post_id, presence: true
  validates :count, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post

  validates :tag_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  before_validation :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: VALID_EMAIL_REGEX

  has_many :stats, dependent: :destroy
  has_many :starred_posts, through: :stars, source: :post

  has_many :favourites, dependent: :destroy
  has_many :favourited_posts, through: :favourites, source: :post

  private

  def downcase_email
    self.email.downcase! if email.present?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def average_star(post)
    stars_array = []
    if post.stars.length != 0
      full_star = (post.stars.map{|s| s.count}.sum / post.stars.count.to_f).round
      full_star.times do
        stars_array.push(fa_icon("star"))
      end
      (5-full_star).times do
        stars_array.push(fa_icon("star-o"))
      end
    else
      5.times do
        stars_array.push(fa_icon("star-o"))
      end
    end
    stars_array.join.html_safe
  end

  def display_star(post)
    if post.stars.find_by(user: current_user).nil?
      star = 0
      star_count = 0
    else
      star = post.stars.find_by(user: current_user)
      star_count = star.count
    end
      blank = star_count + 1


    method = (
      if star == 0
        :post
      else
        :patch
      end
    )

    def path(post, star, count)
      if star == 0
        post_stars_path(post, star: {count: count })
      else
        star_path(star, star: {count: count })
      end
    end

    links = []

    1.upto(star_count) do |i|
      links << link_to( fa_icon("star"), path(post, star, i), method: method)
    end


    blank.upto(5) do |i|
      links << link_to( fa_icon("star-o"), path(post, star, i), method: method)
    end

    safe_join(links, ' ')


  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="container">
    <nav class="navbar navbar-default vertical-center">
        <%= link_to 'Home', home_path %>
        |
        <%= link_to 'About', about_path %>
        |
        <%= link_to 'New Posts', new_post_path %>
        |
        <%= link_to 'All Posts', posts_path %>

        <% if user_signed_in? %>
        <div class="pull-right">
          Hello <%= link_to current_user.first_name.titleize, edit_user_path(current_user) %>
          |
          <%= link_to 'Sign Out', sessions_path, method: :delete%>
          |
          <%= link_to 'Update Your Password', edit_password_path(current_user) %>
          |
          <%= link_to 'Your Favourite Posts', user_favourites_path(current_user) %>
        </div>
        <% else %>
          <%= link_to 'Sign up', new_user_path %>
          |
          <%= link_to 'Sign in', new_session_path %>
        <%end%>
    </nav>
    <% if notice || alert %>
       <div class="alert alert-<%= notice ? 'success' : 'danger'%> alert-dismissable" role="alert">
         <%= notice || alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <br>
    <br>
    <div class="row">
      <div class="col-md-12 center">
        <%= csrf_meta_tag%>
        <%= yield %>
      </div>
    </div>
  </body>
</html>